import random

QUOTES = [
    ("It is not the mountain we conquer, but ourselves.", "Edmund Hillary"),
    ("The only way to do great work is to love what you do.", "Steve Jobs"),
    ("We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "Aristotle"),
    ("The mind is everything. What you think you become.", "Buddha"),
    ("An investment in knowledge pays the best interest.", "Benjamin Franklin"),
    ("The beautiful thing about learning is that no one can take it away from you.", "B.B. King"),
    ("It does not matter how slowly you go as long as you do not stop.", "Confucius"),
    ("The more that you read, the more things you will know.", "Dr. Seuss"),
    ("Education is the most powerful weapon which you can use to change the world.", "Nelson Mandela"),
    ("Live as if you were to die tomorrow. Learn as if you were to live forever.", "Mahatma Gandhi"),
    ("A reader lives a thousand lives before he dies. The man who never reads lives only one.", "George R.R. Martin"),
    ("Not all those who wander are lost.", "J.R.R. Tolkien"),
    ("There is no friend as loyal as a book.", "Ernest Hemingway"),
    ("Until I feared I would lose it, I never loved to read. One does not love breathing.", "Harper Lee"),
    ("So we beat on, boats against the current, borne back ceaselessly into the past.", "F. Scott Fitzgerald"),
    ("It is a far, far better thing that I do, than I have ever done.", "Charles Dickens"),
    ("All we have to decide is what to do with the time that is given us.", "J.R.R. Tolkien"),
    ("Whatever you are, be a good one.", "Abraham Lincoln"),
    ("The secret of getting ahead is getting started.", "Mark Twain"),
    ("I have not failed. I've just found 10,000 ways that won't work.", "Thomas Edison"),
    ("The only limit to our realization of tomorrow is our doubts of today.", "Franklin D. Roosevelt"),
    ("In the middle of difficulty lies opportunity.", "Albert Einstein"),
    ("To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", "Ralph Waldo Emerson"),
    ("It is never too late to be what you might have been.", "George Eliot"),
    ("One cannot think well, love well, sleep well, if one has not dined well.", "Virginia Woolf"),
    ("The world breaks everyone, and afterward, many are strong at the broken places.", "Ernest Hemingway"),
    ("Happiness is not something ready-made. It comes from your own actions.", "Dalai Lama"),
    ("You must be the change you wish to see in the world.", "Mahatma Gandhi"),
    ("I think, therefore I am.", "Rene Descartes"),
    ("The unexamined life is not worth living.", "Socrates"),
    ("That which does not kill us makes us stronger.", "Friedrich Nietzsche"),
    ("To read without reflecting is like eating without digesting.", "Edmund Burke"),
    ("The man who does not read has no advantage over the man who cannot read.", "Mark Twain"),
    ("Knowledge speaks, but wisdom listens.", "Jimi Hendrix"),
    ("Discipline is the bridge between goals and accomplishment.", "Jim Rohn"),
    ("Success is not final, failure is not fatal: it is the courage to continue that counts.", "Winston Churchill"),
    ("The best time to plant a tree was 20 years ago. The second best time is now.", "Chinese Proverb"),
    ("I am not a product of my circumstances. I am a product of my decisions.", "Stephen Covey"),
    ("Do what you can, with what you have, where you are.", "Theodore Roosevelt"),
    ("Knowing yourself is the beginning of all wisdom.", "Aristotle"),
    ("The only true wisdom is in knowing you know nothing.", "Socrates"),
    ("Be the change that you wish to see in the world.", "Mahatma Gandhi"),
    ("Stay hungry, stay foolish.", "Steve Jobs"),
    ("What lies behind us and what lies before us are tiny matters compared to what lies within us.", "Ralph Waldo Emerson"),
    ("The future belongs to those who believe in the beauty of their dreams.", "Eleanor Roosevelt"),
    ("He who opens a school door, closes a prison.", "Victor Hugo"),
    ("Books are a uniquely portable magic.", "Stephen King"),
    ("I have always imagined that Paradise will be a kind of library.", "Jorge Luis Borges"),
    ("Reading is to the mind what exercise is to the body.", "Joseph Addison"),
    ("The doors of wisdom are never shut.", "Benjamin Franklin"),
]


def random_quote() -> tuple[str, str]:
    return random.choice(QUOTES)
